"""initial schema

Revision ID: 65f0715f47d9
Revises: 
Create Date: 2026-09-07 13:51:12.758509
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# 자동 생성은 이 제약을 실행 시점 방언으로 구워 문자열로 박아 둔다. 그러면
# SQLite 문법이 마이그레이션에 남아 PostgreSQL 에서 뜻이 달라지므로, 모델이
# 쓰는 식을 그대로 불러 쓴다 — 제약이 두 엔진에서 같은 규칙이어야 한다.
from app.db.models import failure_reason_is_present


revision: str = '65f0715f47d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_groups',
    sa.Column('group_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value_fixed', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('group_code')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('process', sa.String(length=20), nullable=True),
    sa.Column('stock_uom', sa.String(length=10), nullable=False),
    sa.Column('phase', sa.String(length=10), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('safety_stock', sa.Float(), nullable=True),
    sa.Column('setup_hours', sa.Float(), nullable=True),
    sa.Column('hours_per_unit', sa.Float(), nullable=True),
    sa.CheckConstraint("((item_type = '완제품') = (code LIKE 'FG-%')) AND ((item_type = '반제품') = (code LIKE 'SF-%')) AND ((item_type = '원자재') = (code LIKE 'RM-%'))", name='ck_item_code_prefix'),
    sa.CheckConstraint("item_type <> '반제품' OR shelf_life_days IS NULL", name='ck_item_semi_finished_has_no_shelf_life'),
    sa.CheckConstraint("item_type <> '원자재' OR safety_stock IS NOT NULL", name='ck_item_raw_has_safety_stock'),
    sa.CheckConstraint("item_type IN ('완제품', '반제품', '원자재')", name='ck_item_type'),
    sa.CheckConstraint("phase IN ('초기', '양산')", name='ck_item_phase'),
    sa.CheckConstraint("process IS NULL OR process IN ('수입', '배합', '코팅', '적층경화', '출하')", name='ck_item_process'),
    sa.CheckConstraint("stock_uom IN ('EA', 'kg', 'L', 'm2')", name='ck_item_stock_uom'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_items_item_type'), ['item_type'], unique=False)

    op.create_table('non_working_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name='ck_non_working_period_ends_after_start'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('partner_type', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("partner_type IN ('공급사', '고객사')", name='ck_partner_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partners_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_partners_partner_type'), ['partner_type'], unique=False)

    op.create_table('risk_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_statuses_risk_key'), ['risk_key'], unique=True)

    op.create_table('bom_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_item_id', sa.Integer(), nullable=False),
    sa.Column('child_item_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('unit_quantity', sa.Float(), nullable=False),
    sa.CheckConstraint('level IN (1, 2)', name='ck_bom_component_level'),
    sa.CheckConstraint('parent_item_id <> child_item_id', name='ck_bom_component_not_self_referencing'),
    sa.ForeignKeyConstraint(['child_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['parent_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_item_id', 'child_item_id', name='uq_bom_component_parent_child')
    )
    op.create_table('common_codes',
    sa.Column('group_code', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_code'], ['code_groups.group_code'], ),
    sa.PrimaryKeyConstraint('group_code', 'code')
    )
    op.create_table('finished_goods_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=50), nullable=False),
    sa.Column('warehouse', sa.String(length=20), nullable=False),
    sa.Column('qc_status', sa.String(length=20), nullable=False),
    sa.Column('stock_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('produced_date', sa.Date(), nullable=False),
    sa.Column('passed_date', sa.Date(), nullable=True),
    sa.Column('reworked', sa.Boolean(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.CheckConstraint("qc_status IN ('검사 대기', '합격', '불합격')", name='ck_finished_goods_lot_qc_status'),
    sa.CheckConstraint("stock_type <> '불량품' OR qc_status = '불합격'", name='ck_finished_goods_lot_defective_is_rejected'),
    sa.CheckConstraint("(passed_date IS NOT NULL) = (qc_status = '합격')", name='ck_finished_goods_lot_passed_date_matches_status'),
    sa.CheckConstraint('passed_date IS NULL OR passed_date >= produced_date', name='ck_finished_goods_lot_passed_after_produced'),
    sa.CheckConstraint('expiry_date IS NULL OR passed_date IS NOT NULL', name='ck_finished_goods_lot_expiry_needs_passed_date'),
    sa.CheckConstraint("stock_type IN ('양품', '불량품')", name='ck_finished_goods_lot_stock_type'),
    sa.CheckConstraint("warehouse <> '제품창고' OR qc_status = '합격'", name='ck_finished_goods_lot_product_warehouse_holds_passed_only'),
    sa.CheckConstraint("warehouse IN ('생산창고', '제품창고')", name='ck_finished_goods_lot_warehouse'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'lot_number', 'warehouse', name='uq_finished_goods_lot_warehouse')
    )
    with op.batch_alter_table('finished_goods_lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finished_goods_lots_lot_number'), ['lot_number'], unique=False)

    op.create_table('material_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=50), nullable=False),
    sa.Column('warehouse', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.CheckConstraint("warehouse IN ('원재료창고', '생산창고')", name='ck_material_lot_warehouse'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'lot_number', 'warehouse', name='uq_material_lot_warehouse')
    )
    with op.batch_alter_table('material_lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_lots_lot_number'), ['lot_number'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('planned_quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=True)

    op.create_table('purchase_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_quantity', sa.Float(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('planned_quantity', sa.Float(), nullable=False),
    sa.Column('actual_quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nonconformity_attributes',
    sa.Column('group_code', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('measure_kind', sa.String(length=10), nullable=False),
    sa.Column('inspection_item_group', sa.String(length=20), nullable=True),
    sa.Column('inspection_item_code', sa.String(length=30), nullable=True),
    sa.CheckConstraint("group_code = 'NC_REASON'", name='ck_nc_reason_group'),
    sa.CheckConstraint("inspection_item_group IS NULL OR inspection_item_group = 'INSP_ITEM'", name='ck_nonconformity_item_group'),
    sa.CheckConstraint("measure_kind <> '계량' OR inspection_item_code IS NOT NULL", name='ck_nonconformity_measured_needs_item'),
    sa.CheckConstraint('(inspection_item_group IS NULL) = (inspection_item_code IS NULL)', name='ck_nonconformity_item_reference_is_whole'),
    sa.CheckConstraint("measure_kind IN ('계량', '계수')", name='ck_nonconformity_measure_kind'),
    sa.ForeignKeyConstraint(['group_code', 'code'], ['common_codes.group_code', 'common_codes.code'], ),
    sa.ForeignKeyConstraint(['inspection_item_group', 'inspection_item_code'], ['common_codes.group_code', 'common_codes.code'], ),
    sa.PrimaryKeyConstraint('group_code', 'code')
    )
    op.create_table('nonconformity_stage_rules',
    sa.Column('reason_group', sa.String(length=20), nullable=False),
    sa.Column('reason_code', sa.String(length=30), nullable=False),
    sa.Column('stage_group', sa.String(length=20), nullable=False),
    sa.Column('stage_code', sa.String(length=30), nullable=False),
    sa.Column('disposition', sa.String(length=20), nullable=False),
    sa.Column('special_acceptance_allowed', sa.Boolean(), nullable=False),
    sa.CheckConstraint("disposition IN ('반품', '환불', '재작업', '폐기', '등급 하향')", name='ck_stage_rule_disposition'),
    sa.CheckConstraint("reason_group = 'NC_REASON'", name='ck_stage_rule_reason_group'),
    sa.CheckConstraint("stage_group = 'INSP_STAGE'", name='ck_stage_rule_stage_group'),
    sa.ForeignKeyConstraint(['reason_group', 'reason_code'], ['common_codes.group_code', 'common_codes.code'], ),
    sa.ForeignKeyConstraint(['stage_group', 'stage_code'], ['common_codes.group_code', 'common_codes.code'], ),
    sa.PrimaryKeyConstraint('reason_group', 'reason_code', 'stage_group', 'stage_code')
    )
    op.create_table('process_inspection_standards',
    sa.Column('process_group', sa.String(length=20), nullable=False),
    sa.Column('process_code', sa.String(length=30), nullable=False),
    sa.Column('item_group', sa.String(length=20), nullable=False),
    sa.Column('item_code', sa.String(length=30), nullable=False),
    sa.Column('upper_spec_limit', sa.Float(), nullable=True),
    sa.Column('lower_spec_limit', sa.Float(), nullable=True),
    sa.Column('center_line', sa.Float(), nullable=True),
    sa.Column('warning_ratio', sa.Float(), nullable=False),
    sa.Column('sigma', sa.Float(), nullable=True),
    sa.Column('sigma_source', sa.String(length=10), nullable=False),
    sa.Column('time_variant', sa.Boolean(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.CheckConstraint("(sigma IS NULL) = (sigma_source = '미정')", name='ck_standard_sigma_matches_source'),
    sa.CheckConstraint('sigma IS NULL OR sigma > 0', name='ck_standard_sigma_is_positive'),
    sa.CheckConstraint("item_group = 'INSP_ITEM'", name='ck_standard_item_group'),
    sa.CheckConstraint("process_group = 'PROCESS'", name='ck_standard_process_group'),
    sa.CheckConstraint("sigma_source IN ('미정', '임의', '실측')", name='ck_standard_sigma_source'),
    sa.CheckConstraint('(upper_spec_limit IS NULL AND lower_spec_limit IS NULL AND center_line IS NULL) OR (upper_spec_limit IS NOT NULL AND lower_spec_limit IS NOT NULL AND center_line IS NOT NULL)', name='ck_standard_spec_is_all_or_nothing'),
    sa.CheckConstraint('lower_spec_limit IS NULL OR lower_spec_limit < upper_spec_limit', name='ck_standard_spec_order'),
    sa.CheckConstraint('warning_ratio > 0 AND warning_ratio <= 1', name='ck_standard_warning_ratio'),
    sa.ForeignKeyConstraint(['item_group', 'item_code'], ['common_codes.group_code', 'common_codes.code'], ),
    sa.ForeignKeyConstraint(['process_group', 'process_code'], ['common_codes.group_code', 'common_codes.code'], ),
    sa.PrimaryKeyConstraint('process_group', 'process_code', 'item_group', 'item_code')
    )
    op.create_table('purchase_close_attributes',
    sa.Column('group_code', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('responsibility', sa.String(length=10), nullable=False),
    sa.Column('scorecard_axis', sa.String(length=20), nullable=True),
    sa.Column('reorder_default', sa.String(length=10), nullable=False),
    sa.CheckConstraint("group_code = 'PO_CLOSE'", name='ck_po_close_group'),
    sa.CheckConstraint("reorder_default IN ('필요', '불필요', '건별')", name='ck_purchase_close_reorder_default'),
    sa.CheckConstraint("responsibility = '공급사' OR scorecard_axis IS NULL", name='ck_purchase_close_own_fault_has_no_axis'),
    sa.CheckConstraint("responsibility IN ('공급사', '자사')", name='ck_purchase_close_responsibility'),
    sa.CheckConstraint("scorecard_axis IS NULL OR scorecard_axis IN ('수량 준수율', '납기 준수율', '공급 가능성')", name='ck_purchase_close_scorecard_axis'),
    sa.ForeignKeyConstraint(['group_code', 'code'], ['common_codes.group_code', 'common_codes.code'], ),
    sa.PrimaryKeyConstraint('group_code', 'code')
    )
    op.create_table('shift_patterns',
    sa.Column('group_code', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=False),
    sa.Column('ends_at', sa.Time(), nullable=False),
    sa.Column('on_site', sa.Boolean(), nullable=False),
    sa.CheckConstraint("group_code = 'SHIFT'", name='ck_shift_group'),
    sa.ForeignKeyConstraint(['group_code', 'code'], ['common_codes.group_code', 'common_codes.code'], ),
    sa.PrimaryKeyConstraint('group_code', 'code')
    )
    op.create_table('supplier_items',
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('lead_time_hours', sa.Float(), nullable=False),
    sa.Column('purchase_uom_group', sa.String(length=20), nullable=False),
    sa.Column('purchase_uom', sa.String(length=10), nullable=False),
    sa.Column('conversion_factor', sa.Float(), nullable=False),
    sa.CheckConstraint("purchase_uom_group = 'UOM'", name='ck_supplier_item_uom_group'),
    sa.CheckConstraint('conversion_factor > 0', name='ck_supplier_item_conversion_factor'),
    sa.CheckConstraint('lead_time_hours >= 0', name='ck_supplier_item_lead_time_hours'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['purchase_uom_group', 'purchase_uom'], ['common_codes.group_code', 'common_codes.code'], ),
    sa.PrimaryKeyConstraint('partner_id', 'item_id')
    )
    op.create_table('txn_type_attributes',
    sa.Column('group_code', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('total_effect', sa.String(length=10), nullable=False),
    sa.Column('paired_code', sa.String(length=30), nullable=True),
    sa.Column('source_document_type', sa.String(length=30), nullable=False),
    sa.CheckConstraint("group_code = 'TXN_TYPE'", name='ck_txn_type_group'),
    sa.CheckConstraint("total_effect IN ('증가', '감소', '양방향', '불변', '기준점')", name='ck_txn_type_total_effect'),
    sa.ForeignKeyConstraint(['group_code', 'code'], ['common_codes.group_code', 'common_codes.code'], ),
    sa.ForeignKeyConstraint(['group_code', 'paired_code'], ['common_codes.group_code', 'common_codes.code'], ),
    sa.PrimaryKeyConstraint('group_code', 'code')
    )
    op.create_table('quality_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_type', sa.String(length=10), nullable=False),
    sa.Column('inspected_date', sa.Date(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('material_lot_id', sa.Integer(), nullable=True),
    sa.Column('daily_production_id', sa.Integer(), nullable=True),
    sa.Column('finished_goods_lot_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("(inspection_type = 'IQC' AND material_lot_id IS NOT NULL AND daily_production_id IS NULL AND finished_goods_lot_id IS NULL) OR (inspection_type = 'PQC' AND material_lot_id IS NULL AND daily_production_id IS NOT NULL AND finished_goods_lot_id IS NULL) OR (inspection_type = 'OQC' AND material_lot_id IS NULL AND daily_production_id IS NULL AND finished_goods_lot_id IS NOT NULL)", name='ck_quality_inspection_target'),
    sa.CheckConstraint("inspection_type IN ('IQC', 'PQC', 'OQC')", name='ck_quality_inspection_type'),
    sa.CheckConstraint(failure_reason_is_present(), name='ck_quality_inspection_failure_reason'),
    sa.CheckConstraint("result IN ('합격', '불합격')", name='ck_quality_inspection_result'),
    sa.ForeignKeyConstraint(['daily_production_id'], ['daily_productions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['finished_goods_lot_id'], ['finished_goods_lots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_lot_id'], ['material_lots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_inspections_inspection_type'), ['inspection_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_inspections_inspection_type'))

    op.drop_table('quality_inspections')
    op.drop_table('txn_type_attributes')
    op.drop_table('supplier_items')
    op.drop_table('shift_patterns')
    op.drop_table('purchase_close_attributes')
    op.drop_table('process_inspection_standards')
    op.drop_table('nonconformity_stage_rules')
    op.drop_table('nonconformity_attributes')
    op.drop_table('daily_productions')
    op.drop_table('purchase_receipts')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))

    op.drop_table('orders')
    with op.batch_alter_table('material_lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_lots_lot_number'))

    op.drop_table('material_lots')
    with op.batch_alter_table('finished_goods_lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finished_goods_lots_lot_number'))

    op.drop_table('finished_goods_lots')
    op.drop_table('common_codes')
    op.drop_table('bom_components')
    with op.batch_alter_table('risk_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_statuses_risk_key'))

    op.drop_table('risk_statuses')
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partners_partner_type'))
        batch_op.drop_index(batch_op.f('ix_partners_code'))

    op.drop_table('partners')
    op.drop_table('non_working_periods')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_item_type'))
        batch_op.drop_index(batch_op.f('ix_items_code'))

    op.drop_table('items')
    op.drop_table('code_groups')
    # ### end Alembic commands ###
